### ISSUE TITLE
New model structure for services

### ISSUE THREAD

**Issue by abeSanchez** [steevejoseph/bazaar-backend#18]
Service:
- Name
- Tags
- Description
- Photos (Would be nice)
- Owner (User id)
- Options:
   - Option Name
   - Option Description
   - Option Cost

**Comment by steevejoseph** [comment]
Copy, will add to model, drop, then push. Aiming for 11/13.

**Comment by abeSanchez** [comment]
Reopend as options aren't implemented, i think?

**Comment by jwf1112** [comment]
closing as i made a sting for you to put your options into
