### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by jwf1112** [steevejoseph/bazaar-backend#30]
add functionality to give a service one or multiple tags

**Comment by abeSanchez** [comment]
if you can at least give me the ability to add one tag then thats great

**Comment by jwf1112** [comment]
@abeSanchez believe that i got the tags to work as an array you will just want to check the formating of them as it is a little weird, but search will work with them and it is setup for edit and crate just pending a pull request

**Comment by jwf1112** [comment]
closing this for now as it has been added let me know if you find any issues (formatting for the request was a pain in json so just be careful when doing that)
