### ISSUE TITLE
Getting services of a user with no services returns a 500 error.

### ISSUE THREAD

**Issue by steevejoseph** [steevejoseph/bazaar-backend#42]
https://github.com/steevejoseph/bazaar-backend/blob/cf2534fc370dc83a0d8ae0e3402e15c292323be0/api/controllers/services.js#L213

Currently a user having no services is indiscernible from an actual server issue. 

The current workaround is to render the affected components with “user has no services” in either case. I’m not sure if this is a precedent that should be set. In the future, if a server fails, people will think we just lost their data, and while we may think that server is fine, we won’t know that it’s dropping requests.

Can we modify this to return an empty array instead, or update the user model to have services defined as an empty array by default?

**Comment by jwf1112** [comment]
fixed both so a user with no services returns a 404 and an empty services array
