### ISSUE TITLE
Create searchByTag

### ISSUE THREAD

**Issue by abeSanchez** [steevejoseph/bazaar-backend#51]
Given tag(s), return services only services that have that tag. Splitting up the services by tags using the general search we have now would allow users to show up in every category on the home page if they add all the tag names to their description. of course i could filter thru on the front end but this would be nicer.

**Comment by jwf1112** [comment]
just made a basic version need to get it to return all services that contain a match for the list of tags, not exact tags

**Comment by jwf1112** [comment]
closeing since tags matching exactly for a seach is no longer an issue if services only have one tag
