### ISSUE TITLE
Create tokenIsValid

### ISSUE THREAD

**Issue by abeSanchez** [steevejoseph/bazaar-backend#56]
not too big of a deal, but if a user steps away for a while and comes back without having to sign back in, they'll have issues trying to do things that need auth since the token expired?

**Comment by jwf1112** [comment]
i can increase the amount of time that the token is valid how long do you think would be reasonable?

**Comment by abeSanchez** [comment]
it'd be more for know if we should log the user out on a fresh load of a page

**Comment by jwf1112** [comment]
the closest thing i can think of is either making a route to check the authentication or possibly returning a timestamp with the creation of the token and having the front end check the timestamp against the current time (but then you would get into the issues of dealing with time depending on if its based on the users system as their time could be off)

**Comment by abeSanchez** [comment]
hehe okay its not a big deal tbh
